#!/usr/bin/python3

import os
import common
import emscripten

def run():
    if not common.html5Mode:
        common.log("Running...")
        os.chdir(common.targetDir)
        command = common.binaryPath
        if common.isLinux():
            command = "LD_LIBRARY_PATH=" + common.rootPath + "/deps/linux/lib" + ('64' if common.isPlatform64() else '32') + " " + command
        os.system(command)
    else:
        if not common.distributed:
            emscripten.build(common.targetDir)

        emscripten.runServer(common.targetDir)

common.init()
common.build()

run()
