#!/usr/bin/python3

import os
import common
import emscripten
import shutil
import stat

common.init()

if common.distributed:
    common.exitWithError("Required non-distributed gengine.")

common.log("Generating distributed gengine...")

common.build()

distDir = common.rootPath + "/dist"
targetDir = distDir + "/build"
shutil.rmtree(distDir, True)
os.makedirs(targetDir)
emscripten.build(targetDir, targetDir)
shutil.copytree(common.rootPath + "/scripts", distDir + "/scripts")

os.makedirs(distDir + "/deps/common/Ash-Haxe")
shutil.copytree(common.rootPath + "/deps/common/Ash-Haxe/src", distDir + "/deps/common/Ash-Haxe/src")

os.makedirs(distDir + "/src")
shutil.copytree(common.rootPath + "/src/haxe", distDir + "/src/haxe")

os.makedirs(distDir + "/src/bindings/generated/haxe")
shutil.copytree(common.rootPath + "/src/bindings/generated/haxe/gengine", distDir + "/src/bindings/generated/haxe/gengine")

shutil.copy2(common.rootPath + "/scripts/dist/gengine.sh", distDir)
shutil.copy2(common.rootPath + "/scripts/dist/gengine-run.sh", distDir)
shutil.copy2(common.rootPath + "/scripts/dist/gengine-run.bat", distDir)
shutil.copy2(common.rootPath + "/scripts/dist/gengine-compile.sh", distDir)
shutil.copy2(common.rootPath + "/scripts/dist/gengine-compile.bat", distDir)

os.chdir(distDir)
version = input("Enter version: ")
fileName = "gengine-" + version + ".zip"
os.system("echo " + version + " > " + distDir + "/VERSION.txt")
os.system("zip -r " + fileName + " *")
os.system("git tag " + version)
