#!/usr/bin/python3

import os
import common
import emscripten
import shutil
import stat

common.init()

if common.distributed:
    common.exitWithError("Required non-distributed gengine.")

common.log("Generating distributed gengine...")

distDir = common.rootPath + "/dist"
targetDir = distDir + "/build"
shutil.rmtree(distDir, True)
os.makedirs(targetDir)
emscripten.build(targetDir)
shutil.copytree(common.rootPath + "/scripts", distDir + "/scripts")

startFile = distDir + "/start-zsh"
startContent = """#!/bin/zsh
source scripts/activate
export GENGINE_DISTRIBUTED=1
zsh -i
"""

with open(startFile, 'a') as out:
    out.write(startContent)
    out.close

st = os.stat(startFile)
os.chmod(startFile, st.st_mode | stat.S_IEXEC)
