#!/usr/bin/python3

import os
import common

def run():
    if not common.html5Mode:
        common.log("Running...")
        os.chdir(common.targetDir)
        command = common.binaryPath
        if common.isLinux():
            command = "LD_LIBRARY_PATH=" + common.rootPath + "/deps/linux/lib" + ('64' if common.isPlatform64() else '32') + " " + command
        os.system(command)
    else:
        common.log("Running emcc...")
        os.chdir(os.environ['GENGINE']+"/build")
        os.system("emcc -s NO_EXIT_RUNTIME=1 " + ('' if common.debugMode else '-O3') + " --bind gengine" + ('d' if common.debugMode else '') + ".bc -o " + common.targetDir + "/index.html --preload-file " + common.rootPath + "/res/coreData@coreData " + "--preload-file " + common.targetDir + "data@data " + "--use-preload-plugins -s TOTAL_MEMORY=67108864 -s TOTAL_STACK=1048576 --shell-file " + common.rootPath + "/src/shell.html")
        os.chdir(common.targetDir)
        common.log("Running HTTP server...")
        os.system("python2 -m SimpleHTTPServer");


common.sanityCheck()
common.init()
common.build()

run()
