#!/usr/bin/python3

import os
import common
import tempfile
import shutil
import emscripten

def packHtml():
    common.log("Packing in HTML5 mode...")
    current_dir = os.getcwd()
    os.system("rm -rf packed-html5/*")
    os.system("mkdir -p packed-html5")
    emscripten.emcc(common.targetDir, common.targetDir + '/packed-html5', False)
    os.chdir(current_dir)
    os.system("cp -rf " + common.targetDir + "gui packed-html5/gui")
    os.system("cp -rf " + common.targetDir + "generated packed-html5/generated")

def packNative():
    common.log("Packing in native mode...")
    packedDir = "packed-" + ( 'linux' if common.isLinux() else 'win' )
    os.system("rm -rf " + packedDir + "/*")
    os.system("mkdir -p " + packedDir + "/content")
    os.system("mkdir -p " + packedDir + "/bin")
    os.system("cp -rf " + common.targetDir + "/* " + packedDir + "/content/")
    os.system("cp -rf " + common.binaryPath + " " + packedDir + "/bin/")
    os.system("cp -rf " + common.buildPath + "/*.dll " + packedDir + "/bin/")
    os.system("cp -rf " + common.buildPath + "/locales " + packedDir + "/bin/")
    startName =  "start" + ( '' if common.isLinux() else '.bat' )
    os.chdir(packedDir)
    fo = open(startName, "w")

    if not common.isLinux():
        fo.write("cd content && ..\\bin\\gengine.exe\n")

    fo.close()
    os.system("chmod +x " + startName)

common.init()
common.build()

if common.html5Mode:
    packHtml()
else:
    packNative()
